baseURL = 'https://lattejeri.github.io/exp-vault/'
languageCode = 'en-us'
title = 'EXP Vault'
theme = 'PaperMod'

[params]
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "EXP Vault"
Content = "Personal archive, notes, and projects."
