baseURL = 'https://lattejeri.github.io/exp-vault/'
languageCode = 'en-us'
title = 'EXP Vault'
theme = 'risotto'

# Automatically adds content folders (like /posts/) to the navigation menu
sectionPagesMenu = 'main'

[params.theme]
palette = 'tokyo-night-dark'

[params.about]
title = 'EXP Vault'
description = 'Personal archive, notes, and projects.'
logo = '⚡'

[[params.socialLinks]]
icon = 'fab fa-github'
title = 'GitHub'
url = 'https://github.com/lattejeri'
