baseURL = 'https://latterjeri.github.io/exp-vault/'
languageCode = 'en-us'
title = 'EXP Vault'
theme = 'PaperMod'

[params]
  homeInfoParams:
    Title = "EXP Vault"
    Content = "Personal archive, notes, and projects."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
